export const getVerses = (surah_id: number) => {
    switch (surah_id) {
        case 1:
            return require('../data/verses/1.json')
        case 2:
            return require('../data/verses/2.json')
        case 3:
            return require('../data/verses/3.json')
        case 4:
            return require('../data/verses/4.json')
        case 5:
            return require('../data/verses/5.json')
        case 6:
            return require('../data/verses/6.json')
        case 7:
            return require('../data/verses/7.json')
        case 8:
            return require('../data/verses/8.json')
        case 9:
            return require('../data/verses/9.json')
        case 10:
            return require('../data/verses/10.json')
        case 11:
            return require('../data/verses/11.json')
        case 12:
            return require('../data/verses/12.json')
        case 13:
            return require('../data/verses/13.json')
        case 14:
            return require('../data/verses/14.json')
        case 15:
            return require('../data/verses/15.json')
        case 16:
            return require('../data/verses/16.json')
        case 17:
            return require('../data/verses/17.json')
        case 18:
            return require('../data/verses/18.json')
        case 19:
            return require('../data/verses/19.json')
        case 20:
            return require('../data/verses/20.json')
        case 21:
            return require('../data/verses/21.json')
        case 22:
            return require('../data/verses/22.json')
        case 23:
            return require('../data/verses/23.json')
        case 24:
            return require('../data/verses/24.json')
        case 25:
            return require('../data/verses/25.json')
        case 26:
            return require('../data/verses/26.json')
        case 27:
            return require('../data/verses/27.json')
        case 28:
            return require('../data/verses/28.json')
        case 29:
            return require('../data/verses/29.json')
        case 30:
            return require('../data/verses/30.json')
        case 31:
            return require('../data/verses/31.json')
        case 32:
            return require('../data/verses/32.json')
        case 33:
            return require('../data/verses/33.json')
        case 34:
            return require('../data/verses/34.json')
        case 35:
            return require('../data/verses/35.json')
        case 36:
            return require('../data/verses/36.json')
        case 37:
            return require('../data/verses/37.json')
        case 38:
            return require('../data/verses/38.json')
        case 39:
            return require('../data/verses/39.json')
        case 40:
            return require('../data/verses/40.json')
        case 41:
            return require('../data/verses/41.json')
        case 42:
            return require('../data/verses/42.json')
        case 43:
            return require('../data/verses/43.json')
        case 44:
            return require('../data/verses/44.json')
        case 45:
            return require('../data/verses/45.json')
        case 46:
            return require('../data/verses/46.json')
        case 47:
            return require('../data/verses/47.json')
        case 48:
            return require('../data/verses/48.json')
        case 49:
            return require('../data/verses/49.json')
        case 50:
            return require('../data/verses/50.json')
        case 51:
            return require('../data/verses/51.json')
        case 52:
            return require('../data/verses/52.json')
        case 53:
            return require('../data/verses/53.json')
        case 54:
            return require('../data/verses/54.json')
        case 55:
            return require('../data/verses/55.json')
        case 56:
            return require('../data/verses/56.json')
        case 57:
            return require('../data/verses/57.json')
        case 58:
            return require('../data/verses/58.json')
        case 59:
            return require('../data/verses/59.json')
        case 60:
            return require('../data/verses/60.json')
        case 61:
            return require('../data/verses/61.json')
        case 62:
            return require('../data/verses/62.json')
        case 63:
            return require('../data/verses/63.json')
        case 64:
            return require('../data/verses/64.json')
        case 65:
            return require('../data/verses/65.json')
        case 66:
            return require('../data/verses/66.json')
        case 67:
            return require('../data/verses/67.json')
        case 68:
            return require('../data/verses/68.json')
        case 69:
            return require('../data/verses/69.json')
        case 70:
            return require('../data/verses/70.json')
        case 71:
            return require('../data/verses/71.json')
        case 72:
            return require('../data/verses/72.json')
        case 73:
            return require('../data/verses/73.json')
        case 74:
            return require('../data/verses/74.json')
        case 75:
            return require('../data/verses/75.json')
        case 76:
            return require('../data/verses/76.json')
        case 77:
            return require('../data/verses/77.json')
        case 78:
            return require('../data/verses/78.json')
        case 79:
            return require('../data/verses/79.json')
        case 80:
            return require('../data/verses/80.json')
        case 81:
            return require('../data/verses/81.json')
        case 82:
            return require('../data/verses/82.json')
        case 83:
            return require('../data/verses/83.json')
        case 84:
            return require('../data/verses/84.json')
        case 85:
            return require('../data/verses/85.json')
        case 86:
            return require('../data/verses/86.json')
        case 87:
            return require('../data/verses/87.json')
        case 88:
            return require('../data/verses/88.json')
        case 89:
            return require('../data/verses/89.json')
        case 90:
            return require('../data/verses/90.json')
        case 91:
            return require('../data/verses/91.json')
        case 92:
            return require('../data/verses/92.json')
        case 93:
            return require('../data/verses/93.json')
        case 94:
            return require('../data/verses/94.json')
        case 95:
            return require('../data/verses/95.json')
        case 96:
            return require('../data/verses/96.json')
        case 97:
            return require('../data/verses/97.json')
        case 98:
            return require('../data/verses/98.json')
        case 99:
            return require('../data/verses/99.json')
        case 100:
            return require('../data/verses/100.json')
        case 101:
            return require('../data/verses/101.json')
        case 102:
            return require('../data/verses/102.json')
        case 103:
            return require('../data/verses/103.json')
        case 104:
            return require('../data/verses/104.json')
        case 105:
            return require('../data/verses/105.json')
        case 106:
            return require('../data/verses/106.json')
        case 107:
            return require('../data/verses/107.json')
        case 108:
            return require('../data/verses/108.json')
        case 109:
            return require('../data/verses/109.json')
        case 110:
            return require('../data/verses/110.json')
        case 111:
            return require('../data/verses/111.json')
        case 112:
            return require('../data/verses/112.json')
        case 113:
            return require('../data/verses/113.json')
        case 114:
            return require('../data/verses/114.json')
        default:
            return null;
    }
}